### ISSUE TITLE
legands label with inside chart 

### ISSUE THREAD

**Issue by rehamwael** [ciprianciurea/chartjs-plugin-doughnutlabel#10]
hello , 

can I ask how to make my pie chart 
https://jsfiddle.net/rehamhabbas/Lm7ktgfp/1/
like this image ?? 
<img width="239" alt="Screenshot 2019-04-09 at 17 43 27" src="https://user-images.githubusercontent.com/17198176/55810004-8bc2e500-5aef-11e9-9732-298972cb891e.png">

Thank you so much , appreciate the help

**Comment by JohnArcher** [comment]
This plugin does not work with pie charts. So, first you have to set `type: 'doughnut'`

Then add the following object to the plugins object:

```javascript
doughnutlabel: {
    labels: [
        {
            text: '50% Dubai',
            font: {
                size: '14'
            },
            color: "#F38C83"
        },
        {
            text: '36% Abu Dhabi',
            font: {
                size: '14'
            },
            color: "#E173C2"
        },
        {
            text: '14% Fujairah',
            font: {
                size: '14'
            },
            color: "#A176E8"
        }
    ]
}
```

**Comment by ciprianciurea** [comment]
Hi @rehamwael ,
This also doesn't currently allow for different text fonts on the same line of text, it just allows you to configure one font (size, color) for one line. 
I'm thinking maybe to allow for an array of lines, each line consisting of an array of labels (each with its own font configuration). What do you think, would that help?

**Comment by rehamwael** [comment]
thank you for the help actually after integrate the api I create the html and center it inside the legand with tacking datasets backgroundColor 

        ```
var htmlArea = "";
        var i = 0;
        for (var area in cancelledAreas) {
            
            htmlArea += '<p>'+ '<b>' + cancelledAreas[area]+ '</b>'+ ' ' +' '+'<span style="color:'+whereCanceledData.datasets[0].backgroundColor[i]+'">'+ area +'</span>'+'</p>'; 
            i++;
        }
        document.getElementById('js-legend').innerHTML = htmlArea;
```


Thanks

**Comment by JohnArcher** [comment]
@rehamwael Could you provide a jsfiddle how to exactly use this? I am not sure how you put the pieces together. Thanks!
