### ISSUE TITLE
Display Total

### ISSUE THREAD

**Issue by Dave3of5** [ciprianciurea/chartjs-plugin-doughnutlabel#2]
Is there anyway to display the total rather than just static text. Most doughnut charts that I have seen allow the user to display the total as a value in the center.

Do you accept pull requests as I could do this myself.

**Comment by ciprianciurea** [comment]
Hi there, yes I accept pull requests.

**Comment by Dave3of5** [comment]
Fixed by #5.

Thanks for all for the effort I'm now using this in my project !
