### ISSUE TITLE
Recalculate and update label text 

### ISSUE THREAD

**Issue by buckelieg** [ciprianciurea/chartjs-plugin-doughnutlabel#3]
Recalculate and update label text on hover particular doughnut section.
The case is when I roll over particular sector I want some calculated value appear inside chart label.
The default calculated value is the percentage that occupies hovered section against all others.
The label is the dataset label of the selected section.

I am thinking of some callbacks to do this. Is it possible?

**Comment by KevinJue** [comment]
@buckelieg do you find a solution i can share with us ?
