### ISSUE TITLE
Add support for dynamic text

### ISSUE THREAD

**Issue by jonathancounihan** [ciprianciurea/chartjs-plugin-doughnutlabel#5]
Add the ability for the label text to be created via a function, to support dynamically changing text.

**Comment by ciprianciurea** [comment]
Hi @jonathancounihan, could you please add here a usage example for such a function to dynamically set the text? The way I do that is by dynamically generate my labels outside of the doughnut (based on the data that I have) and then statically set the doughnut label.

**Comment by ciprianciurea** [comment]
Fixes #6 , #5

**Comment by jonathancounihan** [comment]
sure @ciprianciurea, will do so. The basic one I can think of is when the legend is displayed and you toggle a segments visibility as shown here:

![chartjsdoughnutlabels](https://user-images.githubusercontent.com/5243816/48367594-973deb80-e6ca-11e8-84a1-3277838edf28.gif)

The relevant code, using the changes I made:

```
text: function() {
  var total = cht.config.data.datasets[0]._meta[0].total;
  return total;
},
```

**Comment by ciprianciurea** [comment]
Thanks @jonathancounihan , managed to update the samples in the meantime.

**Comment by JohnArcher** [comment]
The code @jonathancounihan posted does not work here (chart.js 2.8.0). `_meta[0]` is not defined. I had to use this: `chart.data.datasets[0]._meta[Object.keys(theChart.data.datasets[0]._meta)[0]].total`

My other problem with your example is that I have no access to `cht` in this scope in my project. So I would like to do a PR which passes the chart object to the `text()` function (similar to other Chart.js plugins).

**Comment by JohnArcher** [comment]
#11

**Comment by JohnArcher** [comment]
As I had several trouble using the internal `_meta` property you should not use this. As stated in https://github.com/chartjs/Chart.js/issues/4731#issuecomment-328279321 you should use getDatasetMeta () instead.

**Comment by vasyl-shumskyi** [comment]
`chart.getDatasetMeta(0).total` works nicely

**Comment by Eduardops4** [comment]
> Add the ability for the label text to be created via a function, to support dynamically changing text.

Olá boa noite
